import Link from 'next/link';
import { readinessPercentage, type CollegeReadiness } from '@/lib/professional/readiness';
import { requireProfessional,pageNumber } from '@/lib/professional/access';
export default async function ReadinessPage({searchParams}:{searchParams:Promise<{score?:string;page?:string}>}){
 const {client}=await requireProfessional(['EMPLOYER']);const params=await searchParams;const score=Number(params.score??70);const page=pageNumber(params.page);
 const valid=Number.isFinite(score)&&score>=0&&score<=100;
 const {data,error}=valid?await client.rpc('fn_employer_college_readiness',{p_minimum_score:score,p_page:page}):{data:null,error:{message:'Invalid filter'}};
 return <main className="px-4 py-8"><div className="mx-auto max-w-5xl"><Link href="/employer/dashboard">Back to employer dashboard</Link><h1 className="mt-4 text-2xl font-bold">College readiness</h1><p className="mt-3">Compare active college students using their latest employability measurement. Only final (non-provisional) scores qualify. The percentage uses all active college students as its denominator. These counts do not establish suitability for a particular job. Unassessed and provisional students are shown separately. No student names or contact details are shared here.</p>
 <form className="professional-form my-5 flex flex-wrap items-end gap-3"><label>Minimum score (%)<input name="score" type="number" min={0} max={100} step="0.01" required defaultValue={valid?score:70}/></label><button className="rounded-lg px-5 py-3">Compare colleges</button></form>
 {error?<p role="alert">Readiness data could not be loaded. Check your access and filter.</p>:!data?.available?<p role="status" className="rounded-lg border bg-amber-50 p-4">Employability reporting is not configured yet. Contact the platform administrator to check the scoring setup.</p>:<>{!data.colleges?.length && <p>No active colleges to report yet.</p>}<div className="grid gap-4 sm:grid-cols-2">{data.colleges?.map((c: CollegeReadiness)=><section key={c.id} className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{c.name} ({c.code})</h2><p className="mt-3 text-xl font-bold">{c.qualifying_students} meet the {score}% threshold</p><p className="mt-2 text-xl font-bold">{c.active_students > 0 ? `${readinessPercentage(c.qualifying_students, c.active_students)}% of active students` : 'Percentage unavailable: no active students'}</p><p>{c.measured_students} with final scores · {c.active_students} active students</p><p>{c.active_students-c.measured_students} unassessed or provisional</p><p className="mt-2 text-sm">Latest valid measurement: {c.latest_measurement?new Date(c.latest_measurement).toLocaleDateString('en-IN'):'None yet'}</p></section>)}</div><nav className="mt-5 flex gap-3">{page>1&&<Link href={`?score=${score}&page=${page-1}`}>Previous</Link>}<span>Page {page}</span>{page*25<(data.total||0)&&<Link href={`?score=${score}&page=${page+1}`}>Next</Link>}</nav></>}
 </div></main>;
}
