import Link from 'next/link';
import { requireProfessional,pageNumber } from '@/lib/professional/access';
import { reportFilters } from '@/lib/employability/report-filters';
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
 const {client}=await requireProfessional(['SUPER_ADMIN','COLLEGE_ADMIN']);const params=await searchParams;const parsed=reportFilters.safeParse(Object.fromEntries(Object.entries(params).filter(([,v])=>v)));const page=pageNumber(params.page);const threshold=Number(params.threshold??40);
 const valid=parsed.success&&Number.isFinite(threshold)&&threshold>=0&&threshold<=100;
 const {data,error}=valid?await client.rpc('fn_students_needing_support',{p_college_id:params.college||null,p_batch_id:params.batch||null,p_threshold:threshold,p_page:page}):{data:null,error:{}};
 const url=(n:number)=>'?'+new URLSearchParams({...(params.college?{college:params.college}:{}),...(params.batch?{batch:params.batch}:{}),threshold:String(threshold),page:String(n)});
 return <main className="mx-auto max-w-5xl px-4 py-8"><Link href="/college/analytics">Back to analytics</Link><h1 className="mt-5 text-2xl font-bold">Students needing learning support</h1><p className="mt-3">Current college/batch cohort: students with no course enrolments or average course progress below the threshold. Date and course report filters do not apply here.</p><form className="professional-form my-5 flex flex-wrap items-end gap-3"><input type="hidden" name="college" value={params.college||''}/><input type="hidden" name="batch" value={params.batch||''}/><label>Progress below (%)<input type="number" name="threshold" min={0} max={100} step="0.01" defaultValue={valid?threshold:40}/></label><button className="rounded-lg p-3">Filter</button></form>{error?<p role="alert">Support list unavailable. Check your filters and database setup.</p>:<><p>{data.total} students need review.</p>{data.students.map((s: { id: string; full_name: string; register_number: string; college_name: string; batch_name: string | null; enrolments: number; average_progress: number })=><section key={s.id} className="mt-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">{s.full_name} · {s.register_number}</h2><p>{s.college_name} · {s.batch_name||'No batch'}</p><p>{s.enrolments} enrolled courses · {s.average_progress}% average progress</p><Link href={`/college/students/${s.id}`} className="mt-2 inline-block underline">Review learning progress</Link></section>)}<nav className="mt-5 flex gap-4">{page>1&&<Link href={url(page-1)}>Previous</Link>}<span>Page {page}</span>{page*25<data.total&&<Link href={url(page+1)}>Next</Link>}</nav></>}</main>;
}
