import Link from 'next/link';
import { requireProfessional,pageNumber } from '@/lib/professional/access';
import { ProfessionalForm } from '@/components/professional-form';
import { logout } from '@/lib/auth/actions';

export default async function EmployerDashboard({searchParams}:{searchParams:Promise<{page?:string}>}){
 const {client,user}=await requireProfessional(['EMPLOYER']);const page=pageNumber((await searchParams).page);
 const {data:company,error}=await client.from('employer_companies').select('*').eq('user_id',user.id).single();
 if(error||!company||company.status!=='ACTIVE')return <main className="p-6"><h1 className="text-2xl font-bold">Employer access</h1><p className="mt-4">Company access is not available. Contact the platform administrator.</p><form action={logout}><button className="mt-4 rounded-lg p-3">Sign out</button></form></main>;
 const {data:jobs,count,error:jobError}=await client.from('employer_jobs').select('*',{count:'exact'}).eq('company_id',company.id).order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 return <main className="px-4 py-8"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">{company.name}</h1><form action={logout}><button className="rounded-lg p-3">Sign out</button></form></div>
 <Link href="/employer/readiness" className="my-5 inline-block rounded-lg px-4 py-3">Compare college readiness</Link>
 <details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-semibold">Company profile</summary><ProfessionalForm kind="company"><label>Company name<input name="name" required maxLength={200} defaultValue={company.name}/></label><label>Website (optional, HTTPS)<input type="url" name="website" maxLength={2048} defaultValue={company.website||''}/></label><label>About the company<textarea name="description" rows={4} maxLength={5000} defaultValue={company.description}/></label></ProfessionalForm></details>
 <details className="mt-5 rounded-xl border bg-white p-5"><summary className="cursor-pointer font-semibold">Post a job requirement</summary><JobForm/></details>
 <h2 className="mt-8 text-xl font-bold">Your job posts</h2><p className="mt-2">Published posts appear in students’ Job opportunities page. Draft and closed posts stay private. The score threshold is a screening aid, not a guarantee of job suitability.</p>
 {jobError?<p role="alert">Job posts could not be loaded. Check the job migration setup.</p>:<>{!jobs?.length&&<p className="mt-4">No job requirements posted yet.</p>}{jobs?.map(job=><details key={job.id} className="mt-4 rounded-xl border bg-white p-5"><summary className="cursor-pointer font-semibold">{job.title} · {job.status}</summary><p className="mt-3">{job.location} · Score threshold: {job.minimum_score}%</p><Link href={`/employer/readiness?score=${job.minimum_score}`} className="mt-3 inline-block rounded-lg p-3">View matching college counts</Link><JobForm job={job}/></details>)}<nav className="mt-5 flex gap-3">{page>1&&<Link href={`?page=${page-1}`}>Previous</Link>}<span>Page {page}</span>{page*25<(count||0)&&<Link href={`?page=${page+1}`}>Next</Link>}</nav></>}
 </div></main>;
}
function JobForm({job}:{job?:any}){return <ProfessionalForm kind="job"><input type="hidden" name="id" defaultValue={job?.id||''}/><label>Job title<input name="title" required minLength={2} maxLength={200} defaultValue={job?.title||''}/></label><label>Location / remote arrangement<input name="location" required minLength={2} maxLength={200} defaultValue={job?.location||''}/></label><label>Requirements, responsibilities and how to apply<textarea name="requirements" required minLength={20} maxLength={10000} rows={6} defaultValue={job?.requirements||''}/></label><label>Minimum employability score (%)<input name="score" type="number" min={0} max={100} step="0.01" required defaultValue={job?.minimum_score??70}/></label><label>Visibility<select name="status" defaultValue={job?.status||'DRAFT'}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="CLOSED">Closed</option></select></label></ProfessionalForm>;}
